trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
variables:
- group: Release
steps:
- script: |
    wget -c https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-$(jmeterVersion).tgz
    tar -xzf apache-jmeter-$(jmeterVersion).tgz
  displayName: 'Install Apache JMeter'
- script: apache-jmeter-$(jmeterVersion)/bin/./jmeter -n -t LoadTest.jmx -o Results.xml -Jhostname=$(STAGING_HOSTNAME)
  displayName: 'Run Load tests'
- script: |
    sudo apt-get update
    sudo apt-get install xsltproc
    xsltproc JMeter2JUnit.xsl Results.xml > JUnit.xml
  displayName: 'Transform JMeter output to JUnit'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: JUnit.xml